// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CaptchaResp struct {
	CaptchaId  string `json:"captcha_id"`  // 验证码ID
	CaptchaUrl string `json:"captcha_url"` // 验证码图片（base64）
}

type CasbinRuleInfo struct {
	Type     string `json:"type"`     // 权限类型
	Resource string `json:"resource"` // 资源路径
	Action   string `json:"action"`   // 操作类型
}

type ChangePasswordReq struct {
	OldPassword string `json:"old_password" validate:"required"` // 原密码
	NewPassword string `json:"new_password" validate:"required"` // 新密码
}

type CreateDictItemReq struct {
	TypeCode    string `json:"type_code"`            // 字典类型编码
	Label       string `json:"label"`                // 字典标签
	Value       string `json:"value"`                // 字典键值
	Description string `json:"description,optional"` // 字典项描述
	Sort        int    `json:"sort,optional"`        // 排序
	Status      int    `json:"status"`               // 状态: 1:启用, 2:禁用
}

type CreateDictItemResp struct {
	ItemID string `json:"item_id"` // 字典项ID
}

type CreateDictTypeReq struct {
	Name        string `json:"name"`                 // 字典类型名称
	Code        string `json:"code"`                 // 字典类型编码
	Description string `json:"description,optional"` // 字典类型描述
	Status      int    `json:"status"`               // 状态: 1:启用, 2:禁用
}

type CreateDictTypeResp struct {
	TypeID string `json:"type_id"` // 字典类型ID
}

type CreateFactoryReq struct {
	FactoryName  string `json:"factory_name" validate:"required"` // 工厂名称
	Address      string `json:"address"`                          // 工厂地址
	ContactPhone string `json:"contact_phone"`                    // 联系电话
	Status       int    `json:"status,default=1"`                 // 状态
}

type CreateFactoryResp struct {
	FactoryID string `json:"factory_id"` // 工厂ID
}

type CreateMenuReq struct {
	Code      string `json:"code"`               // 菜单code
	Action    string `json:"action"`             // 权限标识
	Type      string `json:"type"`               // 菜单类型
	ParentID  string `json:"parent_id"`          // 父菜单ID
	Name      string `json:"name"`               // 菜单名称
	Path      string `json:"path,optional"`      // 路由路径
	Component string `json:"component,optional"` // 前端组件路径
	Redirect  string `json:"redirect,optional"`  // 重定向路径
	Icon      string `json:"icon,optional"`      // 菜单图标
	Sort      int    `json:"sort,optional"`      // 排序号
	Status    int    `json:"status,optional"`    // 状态 1:启用 2:禁用
}

type CreateMenuResp struct {
	MenuID string `json:"menu_id"` // 菜单ID
}

type CreatePermissionReq struct {
	Name        string `json:"name" validate:"required"`     // 权限名称
	Code        string `json:"code" validate:"required"`     // 权限编码
	Type        string `json:"type" validate:"required"`     // 权限类型(1:菜单menu 2:页面page 3:按钮button 4:接口api 5:数据data)
	Resource    string `json:"resource" validate:"required"` // 资源路径
	Action      string `json:"action" validate:"required"`   // 操作类型
	ParentID    string `json:"parent_id,optional"`           // 父级ID
	Description string `json:"description,optional"`         // 描述
	Status      int    `json:"status,optional"`              // 状态(1:启用 2:禁用)
	MenuID      string `json:"menu_id,optional"`             // 菜单ID
}

type CreatePermissionResp struct {
	PermissionID string `json:"permission_id"` // 权限规则ID
}

type CreateProductReq struct {
	ProductName   string `json:"product_name" validate:"required"` // 商品名称
	Unit          string `json:"unit"`                             // 单位
	PurchasePrice string `json:"purchase_price"`                   // 采购价格
	SalePrice     string `json:"sale_price"`                       // 销售价格
	CurrentStock  int    `json:"current_stock,default=0"`          // 当前库存
	MinStock      int    `json:"min_stock,default=0"`              // 最小库存预警
	Status        int    `json:"status,default=1"`                 // 状态
	FactoryID     string `json:"factory_id,optional"`              // 所属工厂ID
}

type CreateProductResp struct {
	ProductID string `json:"product_id"` // 商品ID
}

type CreateRoleReq struct {
	Name        string `json:"name"`                 // 角色名
	Code        string `json:"code"`                 // 角色编码
	Description string `json:"description,optional"` // 角色描述
	Status      int    `json:"status"`               // 状态: 1:启用, 2:禁用
	Sort        int    `json:"sort,optional"`        // 排序
}

type CreateRoleResp struct {
	RoleID string `json:"role_id"` // 角色ID
}

type CreateTenantReq struct {
	Name        string `json:"name" validate:"required"`
	Code        string `json:"code" validate:"required"`
	Description string `json:"description,optional" validate:"omitempty"`
	Status      int    `json:"status,optional" validate:"omitempty"`
}

type CreateTenantResp struct {
	TenantID string `json:"tenant_id"`
}

type CreateUserReq struct {
	UserName string   `json:"user_name"`         // 用户名
	Name     string   `json:"name"`              // 姓名
	Password string   `json:"password"`          // 密码
	Status   int      `json:"status"`            // 状态
	Phone    string   `json:"phone"`             // 手机号
	Email    string   `json:"email,optional"`    // 邮箱
	Sex      int      `json:"sex,optional"`      // 性别
	Avatar   string   `json:"avatar,optional"`   // 头像
	RoleIDs  []string `json:"role_ids,optional"` // 角色ID列表
}

type CreateUserResp struct {
	UserID string `json:"user_id"` // 用户ID
}

type DeleteDictItemReq struct {
	ItemID   string `path:"item_id"`
	TypeCode string `path:"type_code"` // 字典类型编码
}

type DeleteDictTypeReq struct {
	TypeID string `path:"type_id"`
}

type DeleteFactoryReq struct {
	FactoryID string `path:"factory_id" validate:"required"` // 工厂ID
}

type DeleteMenuReq struct {
	MenuID string `path:"menu_id"`
}

type DeletePermissionReq struct {
	PermissionID string `path:"permission_id" validate:"required"` // 权限规则ID
}

type DeleteProductReq struct {
	ProductID string `path:"product_id" validate:"required"` // 商品ID
}

type DeleteRoleReq struct {
	RoleID string `path:"role_id"`
}

type DeleteTenantReq struct {
	TenantID string `path:"tenant_id"`
}

type DeleteUserReq struct {
	UserID string `path:"user_id"`
}

type DictItemAllResp struct {
	List []*DictItemInfo `json:"list"` // 字典项选项列表
}

type DictItemInfo struct {
	ItemID      string `json:"item_id"`     // 字典项ID
	TypeCode    string `json:"type_code"`   // 字典类型编码
	Label       string `json:"label"`       // 字典标签
	Value       string `json:"value"`       // 字典键值
	Description string `json:"description"` // 字典项描述
	Sort        int    `json:"sort"`        // 排序
	Status      int    `json:"status"`      // 状态
	CreatedAt   int64  `json:"created_at"`  // 创建时间
}

type DictItemListReq struct {
	PageRequest
	TypeCode string `path:"type_code"`       // 字典类型编码
	Label    string `form:"label,optional"`  // 字典标签
	Status   int    `form:"status,optional"` // 状态
}

type DictItemListResp struct {
	Page *PageResponse   `json:"page"` // 分页
	List []*DictItemInfo `json:"list"` // 字典数据列表
}

type DictTypeInfo struct {
	TypeID      string `json:"type_id"`     // 字典类型ID
	Name        string `json:"name"`        // 字典类型名称
	Code        string `json:"code"`        // 字典类型编码
	Description string `json:"description"` // 字典类型描述
	Status      int    `json:"status"`      // 状态
	CreatedAt   int64  `json:"created_at"`  // 创建时间
}

type DictTypeListReq struct {
	PageRequest
	Name   string `form:"name,optional"`   // 字典类型名称
	Code   string `form:"code,optional"`   // 字典类型编码
	Status int    `form:"status,optional"` // 状态
}

type DictTypeListResp struct {
	Page *PageResponse   `json:"page"` // 分页
	List []*DictTypeInfo `json:"list"` // 字典类型列表
}

type FactoryInfo struct {
	FactoryID    string `json:"factory_id"`    // 工厂ID
	FactoryName  string `json:"factory_name"`  // 工厂名称
	Address      string `json:"address"`       // 工厂地址
	ContactPhone string `json:"contact_phone"` // 联系电话
	Status       int    `json:"status"`        // 状态
	CreatedAt    int64  `json:"created_at"`    // 创建时间
	UpdatedAt    int64  `json:"updated_at"`    // 更新时间
}

type FactoryListReq struct {
	PageRequest
	FactoryName string `form:"factory_name,optional"` // 工厂名称
	Status      int    `form:"status,optional"`       // 状态
}

type FactoryListResp struct {
	Page *PageResponse  `json:"page"` // 分页
	List []*FactoryInfo `json:"list"` // 工厂列表
}

type GetActiveDevicesResp struct {
	ActiveDevices int `json:"active_devices"` // 当前活跃设备数量
}

type GetAllRolesResp struct {
	List []*RoleInfo `json:"list"` // 角色列表
}

type GetDictItemAllReq struct {
	TypeCode string `path:"type_code"` // 字典类型编码
}

type GetDictItemReq struct {
	ItemID   string `path:"item_id"`
	TypeCode string `path:"type_code"` // 字典类型编码
}

type GetDictTypeReq struct {
	TypeID string `path:"type_id"`
}

type GetFactoryReq struct {
	FactoryID string `path:"factory_id" validate:"required"` // 工厂ID
}

type GetMenuReq struct {
	MenuID string `path:"menu_id"`
}

type GetPermissionReq struct {
	PermissionID string `path:"permission_id" validate:"required"` // 权限规则ID
}

type GetPermissionResp struct {
	PermissionInfo
}

type GetProductReq struct {
	ProductID string `path:"product_id" validate:"required"` // 商品ID
}

type GetResourceTypesResp struct {
	List []*ResourceTypeInfo `json:"list"` // 资源类型列表
}

type GetRolePermissionsReq struct {
	RoleCode string `path:"role_code"` // 角色ID
}

type GetRolePermissionsResp struct {
	List []*Permission `json:"list"` // 权限列表
}

type GetRoleReq struct {
	RoleID string `path:"role_id"`
}

type GetTenantReq struct {
	TenantID string `path:"tenant_id"`
}

type GetTenantResp struct {
	TenantInfo
}

type GetUserReq struct {
	UserID string `path:"user_id"`
}

type GetUserRolesReq struct {
	UserID string `path:"user_id"` // 用户ID
}

type GetUserRolesResp struct {
	List []*RoleInfo `json:"list"` // 角色列表
}

type IDRequest struct {
	ID int `json:"id"` // ID
}

type InventoryInfo struct {
	InventoryID   string `json:"inventory_id"`   // 库存记录ID
	ProductID     string `json:"product_id"`     // 商品ID
	ProductName   string `json:"product_name"`   // 商品名称
	OperationType string `json:"operation_type"` // 操作类型
	Quantity      int    `json:"quantity"`       // 操作数量
	UnitPrice     string `json:"unit_price"`     // 单价
	TotalAmount   string `json:"total_amount"`   // 总金额
	OperatorID    string `json:"operator_id"`    // 操作人ID
	OperatorName  string `json:"operator_name"`  // 操作人姓名
	Remark        string `json:"remark"`         // 备注
	OperationTime int64  `json:"operation_time"` // 操作时间
	BeforeStock   int    `json:"before_stock"`   // 操作前库存
	AfterStock    int    `json:"after_stock"`    // 操作后库存
}

type InventoryListReq struct {
	PageRequest
	ProductID     string `form:"product_id,optional"`     // 商品ID
	OperationType string `form:"operation_type,optional"` // 操作类型
	OperatorID    string `form:"operator_id,optional"`    // 操作人ID
	StartTime     string `form:"start_time,optional"`     // 开始时间
	EndTime       string `form:"end_time,optional"`       // 结束时间
}

type InventoryListResp struct {
	Page *PageResponse    `json:"page"` // 分页
	List []*InventoryInfo `json:"list"` // 库存记录列表
}

type InventoryOperationResp struct {
	InventoryID string `json:"inventory_id"` // 库存记录ID
	Message     string `json:"message"`      // 操作结果信息
}

type ListPermissionReq struct {
	PageRequest
	Name     string `form:"name,optional"`     // 权限名称
	Code     string `form:"code,optional"`     // 权限编码
	Type     string `form:"type,optional"`     // 权限类型
	Resource string `form:"resource,optional"` // 资源路径
	Action   int    `form:"action,optional"`   // 操作类型
	Status   int    `form:"status,optional"`   // 状态
}

type ListPermissionResp struct {
	Page *PageResponse     `json:"page"` // 分页信息
	List []*PermissionInfo `json:"list"` // 权限规则列表
}

type ListTenantReq struct {
	PageRequest
	Status int `form:"status" validate:"omitempty"` // 状态
}

type ListTenantResp struct {
	Page *PageResponse `json:"page"` // 分页
	List []*TenantInfo `json:"list"` // 租户列表
}

type LoginLogInfo struct {
	LogID     string `json:"log_id"`     // 记录ID
	UserID    string `json:"user_id"`    // 用户ID
	UserName  string `json:"user_name"`  // 用户名
	IP        string `json:"ip"`         // 登录IP
	UserAgent string `json:"user_agent"` // 用户代理
	Status    int    `json:"status"`     // 登录状态
	Message   string `json:"message"`    // 状态信息
	CreatedAt int64  `json:"created_at"` // 创建时间
}

type LoginLogListReq struct {
	PageRequest
	UserName  string `form:"user_name,optional"`  // 用户名
	IP        string `form:"ip,optional"`         // 登录IP
	Status    int    `form:"status,optional"`     // 登录状态
	StartTime string `form:"start_time,optional"` // 开始时间
	EndTime   string `form:"end_time,optional"`   // 结束时间
}

type LoginLogListResp struct {
	Page *PageResponse   `json:"page"` // 分页信息
	List []*LoginLogInfo `json:"list"` // 登录记录列表
}

type LoginReq struct {
	UserName  string `json:"username" validate:"required"`   // 用户名
	Password  string `json:"password" validate:"required"`   // 密码
	CaptchaId string `json:"captcha_id" validate:"required"` // 验证码ID
	Captcha   string `json:"captcha" validate:"required"`    // 验证码
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserID       string `json:"user_id"`
	UserName     string `json:"user_name"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
}

type MenuInfo struct {
	MenuID    string `json:"menu_id"`    // 菜单ID
	Code      string `json:"code"`       // 菜单code
	ParentID  string `json:"parent_id"`  // 父菜单ID
	Name      string `json:"name"`       // 菜单名称
	Path      string `json:"path"`       // 路由路径
	Component string `json:"component"`  // 前端组件路径
	Redirect  string `json:"redirect"`   // 重定向路径
	Icon      string `json:"icon"`       // 菜单图标
	Sort      int    `json:"sort"`       // 排序号
	Type      string `json:"type"`       // 菜单类型
	Status    int    `json:"status"`     // 状态
	CreatedAt int64  `json:"created_at"` // 创建时间
}

type MenuListReq struct {
	PageRequest
	Name   string `form:"name,optional"`   // 菜单名称
	Type   string `form:"type,optional"`   // 菜单类型
	Status int    `form:"status,optional"` // 状态
}

type MenuListResp struct {
	Page *PageResponse `json:"page"` // 分页
	List []*MenuInfo   `json:"list"` // 菜单列表
}

type MenuTree struct {
	MenuID    string         `json:"menu_id"`   // 菜单ID
	Code      string         `json:"code"`      // 菜单code
	ParentID  string         `json:"parent_id"` // 父菜单ID
	Name      string         `json:"name"`      // 菜单名称
	Path      string         `json:"path"`      // 路由路径
	Component string         `json:"component"` // 前端组件路径
	Redirect  string         `json:"redirect"`  // 重定向路径
	Icon      string         `json:"icon"`      // 菜单图标
	Sort      int            `json:"sort"`      // 排序号
	Type      string         `json:"type"`      // 菜单类型
	Status    int            `json:"status"`    // 状态
	Children  []*MenuTree    `json:"children"`  // 子菜单
	Rule      CasbinRuleInfo `json:"rule"`      // 权限规则信息
}

type MenuTreeResp struct {
	List []*MenuTree `json:"list"` // 菜单树列表
}

type PageJsonRequest struct {
	Current  int `json:"current"`   // 当前页
	PageSize int `json:"page_size"` // 每页大小
}

type PageRequest struct {
	Current  int `form:"page,default=1" validate:"required,gte=1"`               // 当前页
	PageSize int `form:"page_size,default=10" validate:"required,gte=1,lte=100"` // 每页大小
}

type PageResponse struct {
	Total           int `json:"total"`             // 总数
	PageSize        int `json:"page_size"`         // 当前页大小
	RequestPageSize int `json:"request_page_size"` // 请求页大小
	Current         int `json:"current"`           // 当前页
}

type Permission struct {
	Resource string `json:"resource"` // 资源
	Action   string `json:"action"`   // 操作类型
	Type     string `json:"type"`     // 权限类型
}

type PermissionInfo struct {
	ID           string `json:"id"`            // 权限规则ID
	TenantCode   string `json:"tenant_code"`   // 租户编码
	PermissionID string `json:"permission_id"` // 权限规则ID
	Name         string `json:"name"`          // 权限名称
	Code         string `json:"code"`          // 权限编码
	Type         string `json:"type"`          // 权限类型
	Resource     string `json:"resource"`      // 资源路径
	Action       string `json:"action"`        // 操作类型
	ParentID     string `json:"parent_id"`     // 父级ID
	Description  string `json:"description"`   // 描述
	Status       int    `json:"status"`        // 状态
	MenuID       string `json:"menu_id"`       // 菜单ID
	CreatedAt    int64  `json:"created_at"`    // 创建时间
}

type ProductInReq struct {
	ProductID  string `json:"product_id" validate:"required"`    // 商品ID
	Quantity   int    `json:"quantity" validate:"required,gt=0"` // 入库数量
	UnitPrice  string `json:"unit_price"`                        // 单价
	OperatorID string `json:"operator_id" validate:"required"`   // 操作人ID
	Remark     string `json:"remark"`                            // 备注
}

type ProductInfo struct {
	ProductID     string `json:"product_id"`     // 商品ID
	ProductName   string `json:"product_name"`   // 商品名称
	Unit          string `json:"unit"`           // 单位
	PurchasePrice string `json:"purchase_price"` // 采购价格
	SalePrice     string `json:"sale_price"`     // 销售价格
	CurrentStock  int    `json:"current_stock"`  // 当前库存
	MinStock      int    `json:"min_stock"`      // 最小库存预警
	Status        int    `json:"status"`         // 状态
	FactoryID     string `json:"factory_id"`     // 所属工厂ID
	FactoryName   string `json:"factory_name"`   // 工厂名称
	CreatedAt     int64  `json:"created_at"`     // 创建时间
	UpdatedAt     int64  `json:"updated_at"`     // 更新时间
}

type ProductListReq struct {
	PageRequest
	ProductName string `form:"product_name,optional"` // 商品名称
	FactoryID   string `form:"factory_id,optional"`   // 工厂ID
	Status      int    `form:"status,optional"`       // 状态
}

type ProductListResp struct {
	Page *PageResponse  `json:"page"` // 分页
	List []*ProductInfo `json:"list"` // 商品列表
}

type ProductOutReq struct {
	ProductID  string `json:"product_id" validate:"required"`    // 商品ID
	Quantity   int    `json:"quantity" validate:"required,gt=0"` // 出库数量
	UnitPrice  string `json:"unit_price"`                        // 单价
	OperatorID string `json:"operator_id" validate:"required"`   // 操作人ID
	Remark     string `json:"remark"`                            // 备注
}

type ProductStockReq struct {
	ProductID string `form:"product_id,optional"` // 商品ID
	FactoryID string `form:"factory_id,optional"` // 工厂ID
}

type ProductStockResp struct {
	List []*StockInfo `json:"list"` // 库存信息列表
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token" validate:"required"` // 刷新令牌
}

type RefreshTokenResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token,omitempty"` // 可选：可以返回新的refresh token
}

type RegisterReq struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
	Name     string `json:"nick_name"`
	Avatar   string `json:"avatar,optional"`
	Phone    string `json:"phone"`
	Email    string `json:"email,optional"`
	Sex      int    `json:"sex,optional"`
}

type RegisterResp struct {
	UserID string `json:"user_id"`
}

type ResetPasswordReq struct {
	UserID      string `json:"user_id" validate:"required"`      // 用户ID
	NewPassword string `json:"new_password" validate:"required"` // 新密码
}

type ResourceTypeInfo struct {
	Type      string   `json:"type"`       // 资源类型
	Actions   []string `json:"actions"`    // 可用操作
	DataRules []string `json:"data_rules"` // 数据规则（仅对数据权限类型有效）
}

type RoleInfo struct {
	RoleID      string `json:"role_id"`     // 角色ID
	Name        string `json:"name"`        // 角色名
	Code        string `json:"code"`        // 角色编码
	Description string `json:"description"` // 角色描述
	Status      int    `json:"status"`      // 状态
	Sort        int    `json:"sort"`        // 排序
	CreatedAt   int64  `json:"created_at"`  // 创建时间
}

type RoleListInfo struct {
	RoleID string `json:"role_id"` // 角色ID
	Name   string `json:"name"`    // 角色名
	Code   string `json:"code"`    // 角色编码
	Sort   int    `json:"sort"`    // 排序
}

type RoleListReq struct {
	PageRequest
	Name   string `form:"name,optional"`   // 角色名
	Code   string `form:"code,optional"`   // 角色编码
	Status int    `form:"status,optional"` // 状态
}

type RoleListResp struct {
	Page *PageResponse `json:"page"` // 分页
	List []*RoleInfo   `json:"list"` // 角色列表
}

type SetRolePermissionsReq struct {
	RoleCode       string        `path:"role_code" validate:"required"`       // 角色ID
	PermissionList []*Permission `json:"permission_list" validate:"required"` // 权限列表
}

type SetUserRolesReq struct {
	UserID       string   `path:"user_id"`                            // 用户ID
	RoleCodeList []string `json:"role_code_list" validate:"required"` // 角色Code列表
}

type StatisticsReq struct {
}

type StatisticsResp struct {
	TotalProducts      int    `json:"total_products"`       // 商品总数
	ActiveProducts     int    `json:"active_products"`      // 启用商品数
	TotalStock         int    `json:"total_stock"`          // 总库存数量
	TotalStockValue    string `json:"total_stock_value"`    // 总库存价值
	LowStockProducts   int    `json:"low_stock_products"`   // 低库存商品数
	TotalInQuantity    int    `json:"total_in_quantity"`    // 总入库数量
	TotalInAmount      string `json:"total_in_amount"`      // 总入库金额
	TotalOutQuantity   int    `json:"total_out_quantity"`   // 总出库数量
	TotalOutAmount     string `json:"total_out_amount"`     // 总出库金额
	TotalSalesAmount   string `json:"total_sales_amount"`   // 总销售金额
	TotalSalesQuantity int    `json:"total_sales_quantity"` // 总销售数量
}

type StatusRequest struct {
	ID     int `json:"id"`     // ID
	Status int `json:"status"` // 状态
}

type StockInfo struct {
	ProductID     string `json:"product_id"`     // 商品ID
	ProductName   string `json:"product_name"`   // 商品名称
	FactoryID     string `json:"factory_id"`     // 工厂ID
	FactoryName   string `json:"factory_name"`   // 工厂名称
	CurrentStock  int    `json:"current_stock"`  // 当前库存
	MinStock      int    `json:"min_stock"`      // 最小库存预警
	Unit          string `json:"unit"`           // 单位
	PurchasePrice string `json:"purchase_price"` // 采购价格
	SalePrice     string `json:"sale_price"`     // 销售价格
	Status        int    `json:"status"`         // 状态
	IsLowStock    bool   `json:"is_low_stock"`   // 是否低库存
}

type TenantInfo struct {
	TenantID    string `json:"tenant_id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Status      int    `json:"status"`
}

type TimeRange struct {
	StartTime string `form:"start_time,optional"` // 开始时间
	EndTime   string `form:"end_time,optional"`   // 结束时间
}

type UpdateDictItemReq struct {
	TypeCode    string `json:"type_code"` // 字典类型编码
	ItemID      string `path:"item_id"`
	Label       string `json:"label,optional"`       // 字典标签
	Value       string `json:"value,optional"`       // 字典键值
	Description string `json:"description,optional"` // 字典项描述
	Sort        int    `json:"sort,optional"`        // 排序
	Status      int    `json:"status,optional"`      // 状态
}

type UpdateDictTypeReq struct {
	TypeID      string `path:"type_id"`
	Name        string `json:"name,optional"`        // 字典类型名称
	Description string `json:"description,optional"` // 字典类型描述
	Status      int    `json:"status,optional"`      // 状态
}

type UpdateFactoryReq struct {
	FactoryID    string `path:"factory_id" validate:"required"` // 工厂ID
	FactoryName  string `json:"factory_name,optional"`          // 工厂名称
	Address      string `json:"address,optional"`               // 工厂地址
	ContactPhone string `json:"contact_phone,optional"`         // 联系电话
	Status       int    `json:"status,optional"`                // 状态
}

type UpdateMenuReq struct {
	MenuID    string `path:"menu_id"`
	Name      string `json:"name,optional"`      // 菜单名称
	Path      string `json:"path,optional"`      // 路由路径
	Component string `json:"component,optional"` // 前端组件路径
	Redirect  string `json:"redirect,optional"`  // 重定向路径
	Icon      string `json:"icon,optional"`      // 菜单图标
	Sort      int    `json:"sort,optional"`      // 排序号
	Status    int    `json:"status,optional"`    // 状态
	ParentID  string `json:"parent_id"`          // 父菜单ID
}

type UpdatePermissionReq struct {
	PermissionID string `path:"permission_id"`        // 权限规则ID
	Name         string `json:"name,optional"`        // 权限名称
	Type         string `json:"type,optional"`        // 权限类型
	Resource     string `json:"resource,optional"`    // 资源路径
	Action       string `json:"action,optional"`      // 操作类型
	ParentID     string `json:"parent_id,optional"`   // 父级ID
	Description  string `json:"description,optional"` // 描述
	Status       int    `json:"status,optional"`      // 状态
	MenuID       string `json:"menu_id,optional"`     // 菜单ID
}

type UpdateProductReq struct {
	ProductID     string `path:"product_id" validate:"required"` // 商品ID
	ProductName   string `json:"product_name,optional"`          // 商品名称
	Unit          string `json:"unit,optional"`                  // 单位
	PurchasePrice string `json:"purchase_price,optional"`        // 采购价格
	SalePrice     string `json:"sale_price,optional"`            // 销售价格
	CurrentStock  int    `json:"current_stock,optional"`         // 当前库存
	MinStock      int    `json:"min_stock,optional"`             // 最小库存预警
	Status        int    `json:"status,optional"`                // 状态
	FactoryID     string `json:"factory_id,optional"`            // 所属工厂ID
}

type UpdateRoleReq struct {
	RoleID      string `path:"role_id"`
	Name        string `json:"name,optional"`        // 角色名
	Description string `json:"description,optional"` // 角色描述
	Status      int    `json:"status,optional"`      // 状态
	Sort        int    `json:"sort,optional"`        // 排序
}

type UpdateTenantReq struct {
	TenantID    string `path:"tenant_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      int    `json:"status"`
}

type UpdateUserReq struct {
	UserID       string   `path:"user_id"`
	Name         string   `json:"name,optional"`
	Email        string   `json:"email,optional"`
	Status       int      `json:"status,optional"`
	Sex          int      `json:"sex,optional"`
	Avatar       string   `json:"avatar,optional"`
	RoleCodeList []string `json:"role_code_list,optional"`
}

type UserInfo struct {
	UserID    string          `json:"user_id"`    // 用户ID
	UserName  string          `json:"user_name"`  // 用户名
	Name      string          `json:"name"`       // 姓名
	Phone     string          `json:"phone"`      // 手机号
	Email     string          `json:"email"`      // 邮箱
	Avatar    string          `json:"avatar"`     // 头像
	Status    int             `json:"status"`     // 状态
	CreatedAt int64           `json:"created_at"` // 创建时间
	RoleList  []*RoleListInfo `json:"role_list"`  // 角色列表
}

type UserListReq struct {
	PageRequest
	Name   string `form:"name,optional"`   // 姓名
	Phone  string `form:"phone,optional"`  // 手机号
	Status int    `form:"status,optional"` // 状态
}

type UserListResp struct {
	Page *PageResponse `json:"page"` // 分页
	List []*UserInfo   `json:"list"` // 用户列表
}
